language: ruby
bundler_args: --without debugging documentation

branches:
  only:
    - master
    - /.+-stable$/

addons:
 code_climate:
   repo_token: c98a4eeafdd6a179fd24c8553ec8445c76027f7501348b22e054e7b360fba034

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-9.0.3.0

matrix:
  allow_failures:
  - rvm: ruby-head

env:
  - LANG="en_US.UTF-8"

install:
  - gem install bundler -v ">= 1.10"
  - rake bootstrap

script: bundle exec rake
